# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "feeds", :force => true do |t|
    t.column "title", :string
    t.column "author", :string
    t.column "url", :string
    t.column "link", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "approved", :integer, :limit => 4, :default => 0, :null => false
    t.column "bounces", :integer, :default => 0
    t.column "feed_data", :text
    t.column "feed_data_type", :string
    t.column "http_headers", :text
    t.column "last_retrieved", :datetime
    t.column "feed_type", :string
  end

  add_index "feeds", ["author"], :name => "author"

  create_table "pages", :force => true do |t|
    t.column "location", :string
    t.column "title", :string
    t.column "content", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "posts", :force => true do |t|
    t.column "feed_id", :integer
    t.column "url", :string
    t.column "title", :string
    t.column "body", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "author", :string
    t.column "guid", :string
    t.column "comment_url", :string
  end

  add_index "posts", ["feed_id", "url"], :name => "feed_id"
  add_index "posts", ["created_at"], :name => "sorting"
  add_index "posts", ["title", "body"], :name => "text"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "settings", :force => true do |t|
    t.column "name", :string
    t.column "value", :string
    t.column "position", :integer
  end

  create_table "sidebar_configs", :force => true do |t|
    t.column "controller", :string
    t.column "active_position", :integer
    t.column "active_config", :text
    t.column "staged_position", :integer
    t.column "staged_config", :text
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "tags_posts", :id => false, :force => true do |t|
    t.column "tag_id", :integer
    t.column "post_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80
    t.column "password", :string, :limit => 40
    t.column "name", :string
    t.column "email", :string
  end

end
